# Generated by Django 4.0 on 2021-12-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books_written',
            field=models.ManyToManyField(null=True, to='core.Books'),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(null=True, to='core.Authors'),
        ),
    ]
