# Generated by Django 4.0 on 2022-01-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchases',
            field=models.ManyToManyField(blank=True, to='core.Books'),
        ),
    ]
