# Generated by Django 4.0 on 2022-01-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books_written',
            field=models.ManyToManyField(blank=True, to='core.Books'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchases',
            field=models.ManyToManyField(to='core.Books'),
        ),
    ]
