# Generated by Django 4.0 on 2021-12-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_authors_books_written_alter_books_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='books_written',
        ),
    ]
