# Generated by Django 3.2.9 on 2021-12-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_batch_identifier_code_alter_books_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='books_written',
            field=models.ManyToManyField(to='core.Books'),
        ),
    ]
