# Generated by Django 4.0.1 on 2022-01-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_books_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.AlterField(
            model_name='authors',
            name='books_written',
            field=models.ManyToManyField(blank=True, related_name='authors', to='core.Books'),
        ),
    ]
