# Generated by Django 4.0.1 on 2022-01-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_books_author_alter_authors_books_written'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books_written',
            field=models.ManyToManyField(blank=True, related_name='author', to='core.Books'),
        ),
    ]
